### ISSUE TITLE
AmpGen rename

### ISSUE THREAD

**Issue by henryiii** [henryiii/decaylanguage#1]
Several bits of code have AmpGen in the title. They should be renamed, since someone does not need to know about or use AmpGen to use DecayLanguage. Here are the current names:

| Name     | Suggested replacement |
|---------|-------------------------|
| `ampgen2goofit.py` | |
| `AmpGen2GooFit` | |
| `Particle.from_AmpGen` | |
| `AmplitudeChain.read_ampgen` | `.read_file` |

**Comment by eduardo-rodrigues** [comment]
BTW, AmpGen is certainly an important package for decaylanguage users, for actual modelling work. A link and basic info in AmpGen in the README file would be useful.

**Comment by eduardo-rodrigues** [comment]
AmpGen can be related to inputs or outputs of the package. In that sense, having an explicit mention of the back-/front-end is not a bad thing in my opinion. so read_ampgen is not bad, since explicit. read_file would only make sense if the tool is 100% connected to the back-/front-end as for example when reading or writing ROOT files with ROOT code.

ampgen2goofit.py in decaylanguage/decay/  seems to make more sense as a package script. Same thing for goofit.py. I would suggest to move these to a scripts/ top-level directory. It does require a bit of a rewriting of these 2 files.
BTW, they both seriously need some documentation in ;-).

Since we are talking about AmpGen and GooFit, anyway: there is also a second goofit.py file under decaylanguage/decay/. This one file lack doc too but more importantly seems specific enough to be put in a dedicated goofit module or even an io module if that makes sense to you.
